# Generated by Django 2.1 on 2020-03-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincust', '0003_auto_20200309_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
